### ISSUE TITLE
Minor typo "receveiver" in walk-through example comment

### ISSUE THREAD

**Issue by fishilico** [gregkh/kdbus#34]
Hi, while reading the kdbus walk-through example, I stumbled upon a typo in a comment in https://git.kernel.org/cgit/linux/kernel/git/gregkh/char-misc.git/tree/samples/kdbus/kdbus-workers.c?h=kdbus&id=2d41f81385089e16aa7ab260ce6819febbee5830#n790 (= https://github.com/gregkh/kdbus/blob/17e1c72cfb2606e105d4ee8dab0f40d9bace17d1/samples/kdbus-workers.c#L790 in GitHub): ``receveiver`` is written instead of ``receiver``.

As this is a minor typo, I don't know if it should wait for kdbus to be merged into the kernel tree and then go through a patch to trivial@kernel.org or if it can be fixed before the merge.

Thanks

**Comment by gregkh** [comment]
On Thu, Mar 12, 2015 at 10:37:28PM -0700, Nicolas Iooss wrote:
> Hi, while reading the kdbus walk-through example, I stumbled upon a typo in a
> comment in https://git.kernel.org/cgit/linux/kernel/git/gregkh/char-misc.git/
> tree/samples/kdbus/kdbus-workers.c?h=kdbus&id=
> 2d41f81385089e16aa7ab260ce6819febbee5830#n790 (= https://github.com/gregkh/
> kdbus/blob/17e1c72cfb2606e105d4ee8dab0f40d9bace17d1/samples/kdbus-workers.c#
> L790 in GitHub): receveiver is written instead of receiver.
> 
> As this is a minor typo, I don't know if it should wait for kdbus to be merged
> into the kernel tree and then go through a patch to trivial@kernel.org or if it
> can be fixed before the merge.

Please just send a patch based on the kdbus patches that were sent to
the kernel mailing list recently.

thanks,

greg k-h

**Comment by fishilico** [comment]
> Please just send a patch based on the kdbus patches that were sent to
> the kernel mailing list recently.

Done in https://lkml.org/lkml/2015/3/15/3 . Thanks,

Nicolas
