### ISSUE TITLE
Final Test attach_flags_mask in kdbus-test

### ISSUE THREAD

**Issue by paulcroize** [gregkh/kdbus#35]
Hello !
I recently install kdbus module along with the 4.0.0-rc5 latest kernel and I can't manage to overcome that error in the final Test attach_flags_mask when executing the test/kdbus-test .
Do you have any clue of what the issue could come from? (below is my term output)
The control node exists and the aaplication bus exists too as long as the test lasts.

Regards,

Paul Croizé

paul@dhcp-15-121:~/dev/gregkh/kdbus$ sudo ./test/kdbus-test
[sudo] password for paul: 
 Starting tests in the same namespaces
 Starting tests with full metadata support
 Starting tests with an attach_flags_mask=0xffffffffffffffff
Testing bus make functions (bus-make) .................................. OK
Testing the HELLO command (hello) ...................................... OK
Testing the BYEBYE command (byebye) .................................... OK
Testing a chat pattern (chat) .......................................... OK
Testing a simple daemon (daemon) ....................................... OK
Testing file descriptor passing (fd-passing) ........................... OK
Testing custom endpoint (endpoint) ..................................... OK
Testing monitor functionality (monitor) ................................ OK
Testing basic name registry functions (name-basics) .................... OK
Testing name registry conflict details (name-conflict) ................. OK
Testing queuing of names (name-queue) .................................. OK
Testing basic message handling (message-basic) ......................... OK
Testing handling of messages with priority (message-prio) .............. OK
Testing message quotas are enforced (message-quota) .................... OK
Testing memory access (memory-access) .................................. OK
Testing timeout (timeout) .............................................. OK
Testing synchronous replies vs. BYEBYE (sync-byebye) ................... OK
Testing synchronous replies (sync-reply) ............................... OK
Testing freeing of memory (message-free) ............................... OK
Testing retrieving connection information (connection-info) ............ OK
Testing updating connection information (connection-update) ............ OK
Testing verifying pools are never writable (writable-pool) ............. OK
Testing policy (policy) ................................................ OK
Testing unprivileged bus access (policy-priv) .......................... OK
Testing policy in user namespaces (policy-ns) .......................... OK
Testing metadata in different namespaces (metadata-ns) ................. OK
Testing adding of matches by id (match-id-add) ......................... OK
Testing removing of matches by id (match-id-remove) .................... OK
Testing replace of matches with the same cookie (match-replace) ........ OK
Testing adding of matches by name (match-name-add) ..................... OK
Testing removing of matches by name (match-name-remove) ................ OK
Testing matching for name changes (match-name-change) .................. OK
Testing matching with bloom filters (match-bloom) ...................... OK
Testing activator connections (activator) .............................. OK
Testing benchmark (benchmark) .......................................... OK
Testing benchmark without using memfds (benchmark-nomemfds) ............ OK
Testing benchmark comparison to UDS (benchmark-uds) .................... OK
Assertion 'attach_count == (KDBUS_TEST_ITEMS_SUM - KDBUS_ITEM_OWNED_NAME - KDBUS_ITEM_TIMESTAMP)' failed in kdbus_test_peers_info(), test-attach-flags.c:355
Assertion 'ret == 0' failed in kdbus_test_attach_flags(), test-attach-flags.c:734
Testing attach flags mask (attach-flags) ............................... ERROR

SUMMARY: 37 tests passed, 0 skipped, 1 failed

**Comment by gregkh** [comment]
Please use the set of patches that was sent to the linux-kernel mailing list for the kdbus code.  If you have issues (like this), please send it to the authors of that patch, or to the systemd mailing list.  It's hard to do debugging through github requests like this, sorry.
