### ISSUE TITLE
Is this alive? Will Linux evolve beyond current status?

### ISSUE THREAD

**Issue by timofonic** [gregkh/kdbus#37]
Hello.

Is this project alive?

A very  geeky friends say Linux needs to be reestructured and fight against conservative ideas, because it has become a very giant project that makes architectural changes nearly impossible.

He praises DragonFly BSD:

- It features many stuff such as [Light Weight Kernel Threads](https://en.wikipedia.org/wiki/Light_Weight_Kernel_Threads). It aims to become better at SMP machines.

- Dillon is developing HAMMER2, people say it looks promising. BTRFS is there, but I see it's development and deployment isn't very strong. Big servers use XFS.

What about DragonFly BSD vs Linux? Why too much separation? I would love BSD and GPL worlds would collaborate to make something better!

Kind regards.

**Comment by gregkh** [comment]
If your friend likes DragonFly BSD, by all means, have them use it, no one forces anyone to use Linux, best of luck to them.

And this has nothing to do with this repo, closing out
